"""empty message

Revision ID: 39f13e6d396d
Revises: b23b3601300a
Create Date: 2022-08-08 08:12:55.640151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39f13e6d396d'
down_revision = 'b23b3601300a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_pokemon_name', table_name='pokemon')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_pokemon_name', 'pokemon', ['name'], unique=False)
    # ### end Alembic commands ###
